apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gohttpserver-gateway
spec:
  servers:
  - port:
      number: 443
      name: https
      protocol: https
    tls:
      mode: SIMPLE
      credentialName: istio-gohttpserver-tls
    hosts:
    - gohttpserveristio.cloudnative-learn.com